### ISSUE TITLE
translate code snippet comments from English to French 

### ISSUE THREAD

**Issue by kim-codes** [NuGet/docs.microsoft.com-nuget.fr-fr#11]
Would it be an acceptable change to translate all comments in code snippets from English to French. 

If we look under [`docs` > `visual-studio-extensibility` > `nuget-api-in-visual-studio.md`](https://github.com/NuGet/docs.microsoft.com-nuget.fr-fr/blob/live/docs/visual-studio-extensibility/nuget-api-in-visual-studio.md) there are many code snippets that the comments are in English. Example under [`Interface IVsPackageInstaller`](https://github.com/NuGet/docs.microsoft.com-nuget.fr-fr/blob/live/docs/visual-studio-extensibility/nuget-api-in-visual-studio.md#interface-ivspackageinstaller)  there are multi-line comments (example lines 102-106) 

>
>     /// The package source to install the package from. This value can be <c>null</c>
>     /// to indicate that the user's configured sources should be used. Otherwise,
>     /// this should be the source path as a string. If the user has credentials
>     /// configured for a source, this value must exactly match the configured source
>     /// value.
> 

This is just one example. I would be willing to update all code snippet comments to French if that would be consdiered helpful.

**Comment by CeciAc** [comment]
Hello @kim-codes 

Unfortunately, this won't be possible since the code snippet is shared among all locales.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
