### ISSUE TITLE
Ou trouver de l'aide sur nuget CLI et ses commandes?

### ISSUE THREAD

**Issue by zosrothko** [NuGet/docs.microsoft.com-nuget.fr-fr#16]
Bonjour

J'ai cherché sur le net un forum ou une liste de discussion... rien trouvé. Donc comment fais t on?

FA

**Comment by ycrumeyrolle** [comment]
https://docs.microsoft.com/fr-fr/nuget/consume-packages/install-use-packages-nuget-cli

**Comment by zosrothko** [comment]
thanks
