### ISSUE TITLE
Possible values in table are translated

### ISSUE THREAD

**Issue by jeremyVignelles** [NuGet/docs.microsoft.com-nuget.fr-fr#8]
In french, the documentation of the possible values of the `IncludeAssets` ... properties are translated.

`all` became `toutes les`, `none` => `aucun` ...

These are values and must not be translated.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [Format PackageReference NuGet (références de package dans des fichiers projet)](https://docs.microsoft.com/fr-fr/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget.fr-fr/blob/live/docs/consume-packages/Package-References-in-Project-Files.md)
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@nokura This is a loc issue for you.

**Comment by kraigb** [comment]
@karann-msft Can you assign to @nokura and follow up to get this corrected?

**Comment by kraigb** [comment]
@jeremyVignelles Thanks for pointing this out!

**Comment by jeremyVignelles** [comment]
Also, sending this issue from the doc itself didn't work and asked me to do that directly from github. I don't know why, but maybe it's because of the `=>` sign?

**Comment by DavidPrio** [comment]
Hello, @jeremyVignelles and @kraigb ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @jeremyVignelles 

Was the issue solved? If not, can you provide me the sentences with the issues so I can escalate it?

Thank you,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @jeremyVignelles ,  
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and reverted the text back to English.  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
